import { NextRequest, NextResponse } from "next/server";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
} from "docx";
import ExcelJS from "exceljs";
import PDFDocument from "pdfkit";
import { writeFile, mkdir } from "fs/promises";
import path from "path";
import { randomUUID } from "crypto";

const DOCS_DIR = path.join(process.cwd(), "generated-docs");

async function ensureDir() {
  await mkdir(DOCS_DIR, { recursive: true });
}

// --- DOCX Generation ---
async function generateDocx(data: DocRequest): Promise<string> {
  const children: (Paragraph | Table)[] = [];

  // Title
  children.push(
    new Paragraph({
      children: [new TextRun({ text: data.title, bold: true, size: 36, font: "Calibri" })],
      heading: HeadingLevel.TITLE,
      spacing: { after: 300 },
    })
  );

  // Subtitle / date
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Nova — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
          size: 20,
          color: "888888",
          font: "Calibri",
        }),
      ],
      spacing: { after: 400 },
    })
  );

  // Sections
  if (data.sections) {
    for (const section of data.sections) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: section.heading, bold: true, size: 28, font: "Calibri" })],
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 300, after: 200 },
        })
      );
      // Split content by newlines
      const lines = section.content.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) continue;
        // Bullet points
        if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: trimmed.slice(2), size: 22, font: "Calibri" })],
              bullet: { level: 0 },
              spacing: { after: 80 },
            })
          );
        } else {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: trimmed, size: 22, font: "Calibri" })],
              spacing: { after: 120 },
            })
          );
        }
      }
    }
  }

  // Table data
  if (data.tableData && data.tableData.length > 0) {
    children.push(
      new Paragraph({
        children: [new TextRun({ text: " " })],
        spacing: { after: 200 },
      })
    );

    const rows = data.tableData.map(
      (row, rowIdx) =>
        new TableRow({
          children: row.map(
            (cell) =>
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      new TextRun({
                        text: String(cell),
                        bold: rowIdx === 0,
                        size: 20,
                        font: "Calibri",
                      }),
                    ],
                    alignment: AlignmentType.LEFT,
                  }),
                ],
                width: { size: 100 / row.length, type: WidthType.PERCENTAGE },
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
                  bottom: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
                  left: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
                  right: { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" },
                },
              })
          ),
        })
    );

    children.push(new Table({ rows, width: { size: 100, type: WidthType.PERCENTAGE } }));
  }

  const doc = new Document({
    sections: [{ children }],
    creator: "Nova by Pixel & Purpose",
  });

  const buffer = await Packer.toBuffer(doc);
  const id = randomUUID();
  const filename = `${id}.docx`;
  await ensureDir();
  await writeFile(path.join(DOCS_DIR, filename), buffer);
  return filename;
}

// --- XLSX Generation ---
async function generateXlsx(data: DocRequest): Promise<string> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Nova by Pixel & Purpose";
  workbook.created = new Date();

  const sheet = workbook.addWorksheet(data.title.slice(0, 31));

  // Title row
  sheet.mergeCells("A1:E1");
  const titleCell = sheet.getCell("A1");
  titleCell.value = data.title;
  titleCell.font = { size: 16, bold: true, color: { argb: "FF1D1D1F" } };
  titleCell.alignment = { vertical: "middle" };
  sheet.getRow(1).height = 30;

  // Date row
  sheet.mergeCells("A2:E2");
  const dateCell = sheet.getCell("A2");
  dateCell.value = `Generated by Nova — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`;
  dateCell.font = { size: 10, color: { argb: "FF888888" } };
  sheet.getRow(2).height = 20;

  let currentRow = 4;

  // Sections as text
  if (data.sections) {
    for (const section of data.sections) {
      const headingCell = sheet.getCell(`A${currentRow}`);
      headingCell.value = section.heading;
      headingCell.font = { size: 13, bold: true, color: { argb: "FF1D1D1F" } };
      currentRow++;

      const lines = section.content.split("\n").filter((l) => l.trim());
      for (const line of lines) {
        const contentCell = sheet.getCell(`A${currentRow}`);
        contentCell.value = line.trim();
        contentCell.font = { size: 11 };
        contentRow(sheet, currentRow);
        currentRow++;
      }
      currentRow++;
    }
  }

  // Table data
  if (data.tableData && data.tableData.length > 0) {
    currentRow++;
    for (let r = 0; r < data.tableData.length; r++) {
      const row = data.tableData[r];
      for (let c = 0; c < row.length; c++) {
        const cell = sheet.getCell(currentRow, c + 1);
        cell.value = isNaN(Number(row[c])) ? String(row[c]) : Number(row[c]);
        if (r === 0) {
          cell.font = { bold: true, size: 11, color: { argb: "FFFFFFFF" } };
          cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FF2A7D8C" } };
        } else {
          cell.font = { size: 11 };
          if (r % 2 === 0) {
            cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF5F5F7" } };
          }
        }
        cell.border = {
          top: { style: "thin", color: { argb: "FFDDDDDD" } },
          bottom: { style: "thin", color: { argb: "FFDDDDDD" } },
          left: { style: "thin", color: { argb: "FFDDDDDD" } },
          right: { style: "thin", color: { argb: "FFDDDDDD" } },
        };
      }
      currentRow++;
    }
    // Auto-width columns
    if (data.tableData[0]) {
      for (let c = 0; c < data.tableData[0].length; c++) {
        const maxLen = Math.max(...data.tableData.map((r) => String(r[c] ?? "").length));
        sheet.getColumn(c + 1).width = Math.min(Math.max(maxLen + 4, 12), 40);
      }
    }
  }

  const id = randomUUID();
  const filename = `${id}.xlsx`;
  await ensureDir();
  const buffer = await workbook.xlsx.writeBuffer();
  await writeFile(path.join(DOCS_DIR, filename), Buffer.from(buffer));
  return filename;
}

function contentRow(sheet: ExcelJS.Worksheet, row: number) {
  sheet.getRow(row).height = 18;
}

// --- PDF Generation ---
async function generatePdf(data: DocRequest): Promise<string> {
  await ensureDir();
  const id = randomUUID();
  const filename = `${id}.pdf`;
  const filePath = path.join(DOCS_DIR, filename);

  const doc = new PDFDocument({ size: "A4", margin: 60 });
  const chunks: Uint8Array[] = [];

  const finished = new Promise<void>((resolve, reject) => {
    doc.on("data", (chunk: Uint8Array) => chunks.push(chunk));
    doc.on("end", () => resolve());
    doc.on("error", reject);
  });

  // Title
  doc.font("Helvetica-Bold").fontSize(24).fillColor("#1d1d1f").text(data.title, { align: "left" });
  doc.moveDown(0.3);
  doc.font("Helvetica").fontSize(10).fillColor("#888888").text(
    `Generated by Nova — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    { align: "left" }
  );
  doc.moveDown(1);

  // Sections
  if (data.sections) {
    for (const section of data.sections) {
      doc.font("Helvetica-Bold").fontSize(15).fillColor("#1d1d1f").text(section.heading);
      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(11).fillColor("#333333");
      const lines = section.content.split("\n");
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed) {
          doc.moveDown(0.3);
          continue;
        }
        if (trimmed.startsWith("- ") || trimmed.startsWith("• ")) {
          doc.text(`  •  ${trimmed.slice(2)}`, { indent: 15 });
        } else {
          doc.text(trimmed, { lineGap: 3 });
        }
      }
      doc.moveDown(0.8);
    }
  }

  // Table
  if (data.tableData && data.tableData.length > 0) {
    doc.moveDown(0.5);
    const cols = data.tableData[0].length;
    const tableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const colWidth = tableWidth / cols;
    const startX = doc.page.margins.left;

    for (let r = 0; r < data.tableData.length; r++) {
      const y = doc.y;
      const isHeader = r === 0;

      if (isHeader) {
        doc.rect(startX, y - 2, tableWidth, 22).fill("#2A7D8C");
      } else if (r % 2 === 0) {
        doc.rect(startX, y - 2, tableWidth, 20).fill("#F5F5F7");
      }

      for (let c = 0; c < cols; c++) {
        doc
          .font(isHeader ? "Helvetica-Bold" : "Helvetica")
          .fontSize(9)
          .fillColor(isHeader ? "#FFFFFF" : "#333333")
          .text(String(data.tableData[r][c] ?? ""), startX + c * colWidth + 4, y, {
            width: colWidth - 8,
            height: 18,
            lineBreak: false,
          });
      }
      doc.y = y + (isHeader ? 22 : 20);
    }
  }

  doc.end();
  await finished;
  await writeFile(filePath, Buffer.concat(chunks));
  return filename;
}

// --- Generate preview HTML for a doc ---
function generatePreviewHtml(data: DocRequest): string {
  let html = `<div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;color:#1d1d1f;padding:24px;max-width:700px">`;
  html += `<h1 style="font-size:22px;margin:0 0 4px">${escapeHtml(data.title)}</h1>`;
  html += `<p style="font-size:12px;color:#888;margin:0 0 20px">Generated by Nova — ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>`;

  if (data.sections) {
    for (const section of data.sections) {
      html += `<h2 style="font-size:16px;margin:20px 0 8px;color:#1d1d1f">${escapeHtml(section.heading)}</h2>`;
      const lines = section.content.split("\n");
      let inList = false;
      for (const line of lines) {
        const t = line.trim();
        if (!t) continue;
        if (t.startsWith("- ") || t.startsWith("• ")) {
          if (!inList) { html += "<ul style='margin:6px 0;padding-left:20px'>"; inList = true; }
          html += `<li style="font-size:13px;line-height:1.6;margin-bottom:3px">${escapeHtml(t.slice(2))}</li>`;
        } else {
          if (inList) { html += "</ul>"; inList = false; }
          html += `<p style="font-size:13px;line-height:1.6;margin:0 0 8px">${escapeHtml(t)}</p>`;
        }
      }
      if (inList) html += "</ul>";
    }
  }

  if (data.tableData && data.tableData.length > 0) {
    html += `<table style="width:100%;border-collapse:collapse;margin-top:16px;font-size:12px">`;
    for (let r = 0; r < data.tableData.length; r++) {
      html += "<tr>";
      for (const cell of data.tableData[r]) {
        if (r === 0) {
          html += `<th style="background:#2A7D8C;color:#fff;padding:8px 10px;text-align:left;font-weight:600">${escapeHtml(String(cell))}</th>`;
        } else {
          html += `<td style="padding:6px 10px;border-bottom:1px solid #eee;${r % 2 === 0 ? "background:#f9f9fb" : ""}">${escapeHtml(String(cell))}</td>`;
        }
      }
      html += "</tr>";
    }
    html += "</table>";
  }

  html += "</div>";
  return html;
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

interface DocSection {
  heading: string;
  content: string;
}

interface DocRequest {
  type: "docx" | "xlsx" | "pdf";
  title: string;
  description?: string;
  sections?: DocSection[];
  tableData?: (string | number)[][];
}

export async function POST(req: NextRequest) {
  try {
    const body: DocRequest = await req.json();
    const { type, title } = body;

    if (!type || !title) {
      return NextResponse.json({ error: "type and title are required" }, { status: 400 });
    }
    if (!["docx", "xlsx", "pdf"].includes(type)) {
      return NextResponse.json({ error: "type must be docx, xlsx, or pdf" }, { status: 400 });
    }

    let filename: string;
    if (type === "docx") {
      filename = await generateDocx(body);
    } else if (type === "xlsx") {
      filename = await generateXlsx(body);
    } else {
      filename = await generatePdf(body);
    }

    const previewHtml = generatePreviewHtml(body);

    return NextResponse.json({
      success: true,
      doc: {
        id: filename.replace(/\.\w+$/, ""),
        type,
        title,
        description: body.description,
        downloadUrl: `/api/docs/download/${filename}`,
        previewHtml,
        createdAt: Date.now(),
      },
    });
  } catch (err) {
    console.error("Doc generation error:", err);
    return NextResponse.json({ error: "Failed to generate document" }, { status: 500 });
  }
}
